### ISSUE TITLE
Support for logback-access in version 2.0.0

### ISSUE THREAD

**Issue by sondemar** [logfellow/logstash-logback-encoder#1014]
**Is your feature request related to a problem? Please describe.**
With the release of Jetty version 12, the logback-access project became incompatible. The subsequent release, version 2.0.0, now aligns with Jetty 12 requirements, making it necessary for applications utilizing Jetty onwards.

**Describe the solution you'd like**
If feasible, please consider upgrading [logback-access](https://github.com/logfellow/logstash-logback-encoder/blob/b1e7653914fba93baf6042b15d44e54909879e4f/pom.xml#L147) to version [2.0.1](https://github.com/qos-ch/logback-access/releases/tag/v_2.0.1) or later.

**Describe alternatives you've considered**
I did not find any alternative so far.

**Additional context**
More details can be found with [this](https://github.com/qos-ch/logback/issues/719) issue. JDK version [11](https://github.com/qos-ch/logback-access/blob/c39c35410b06e0b990ecf4d18629ae06f0395515/pom.xml#L60) is required.

**Comment by JoergHeinicke5005** [comment]
@philsttr, sorry to approach you directly, but you seem kind of the main/ only maintainer of this project. Thanks!

Is there a chance for this PR to get applied within reasonable time? It's a trivial change of just adapting to the package name change. And would require a major release due to the dropped Java 8 support (raised to Java 11).

**Comment by kiefermat** [comment]
Any news on this? This issue blocks updating to Spring Boot 3.3.

**Comment by stockii** [comment]
Any updates on this? :))
