### ISSUE TITLE
Nacos added appender error

### ISSUE THREAD

**Issue by ncc0706** [logfellow/logstash-logback-encoder#1022]
detail see [https://github.com/alibaba/nacos/issues/11781](https://github.com/alibaba/nacos/issues/11781)

**Comment by philsttr** [comment]
I need more information.  Preferably with reproducible code and config.

**Comment by ncc0706** [comment]
@philsttr 
https://github.com/ncc0706/spring-boot-logstash.git

![image](https://github.com/user-attachments/assets/ae309e99-3f57-436d-bedb-c65bc5f6f7e2)

**Comment by philsttr** [comment]
The error messages that you have highlighted do not look related to logstash-logback-encoder.
The error messages look related to the appenders defined in [naco-logback.xml](https://github.com/alibaba/nacos/blob/develop/distribution/conf/nacos-logback.xml).


I can reproduce the same error messages without using logstash-logback-encoder by replacing this:
```xml
        <appender name="LOGSTASH" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
            <destination>${logstashHost}</destination>
            <encoder charset="UTF-8" class="net.logstash.logback.encoder.LogstashEncoder"/>
        </appender>

```


with this
```xml
        <appender name="LOGSTASH" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%m</pattern>
            </encoder>
        </appender>
```

Since I can reproduce the error messages you see without using logstash-logback-encoder, I do not believe the error messages are caused by logstash-logback-encoder.

**Comment by philsttr** [comment]
You can set `debug="true"` in your logback-spring.xml to help debug.

```xml
<configuration scan="false" debug="true">

```

**Comment by ncc0706** [comment]
Thanks, this is a bug in Nacos.
```
-Dnacos.logging.default.config.enabled=false
```
