### ISSUE TITLE
Release 8.0 source artifact in Maven Central does not contain the source code

### ISSUE THREAD

**Issue by clementdenis** [logfellow/logstash-logback-encoder#1036]
**Describe the bug**
[The source artifact for release 8.0](https://repo1.maven.org/maven2/net/logstash/logback/logstash-logback-encoder/8.0/logstash-logback-encoder-8.0-sources.jar) only contains the sources of a repackaged version of the LMAX Disruptor (in net/logstash/logback/encoder/com/lmax/disruptor).

This is expected given the shade plugin configuration, that only include LMAX Disruption:
https://github.com/logfellow/logstash-logback-encoder/blob/5cd053fbd39d3f0ab711a485069e5c680e5068c1/pom.xml#L389-L426

**Expected behavior**
The source artifact should contain the source of this project as well.

**Comment by philsttr** [comment]
Thanks for the report.  This seems to have been caused by the upgrade to the maven-release-plugin.  For some reason, the `release-profile` from the maven super pom which packages the source jar containing the project sources was not included when 8.0 was built.  The profile was included when 7.4 was built, so it has the correct sources in the source jar.   The maven-shade-plugin later repackages that jar with additional sources from the shaded dependencies.
