### ISSUE TITLE
Authentication object always null in AbstractFieldJsonProvider

### ISSUE THREAD

**Issue by nrvmodi** [logfellow/logstash-logback-encoder#312]
Hello,

I want to print logged in user in logs using `LogstashTcpSocketAppender`.

For that I have created one implementation like below

`public class UserJsonProvider extends AbstractFieldJsonProvider<ILoggingEvent> implements FieldNamesAware<LogstashFieldNames> {

    public static final String FIELD_USER = "user";

    public UserJsonProvider() {
        this.setFieldName(FIELD_USER);
    }

    public String getUser(ILoggingEvent event) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.getName();
        }
        return "NO_USER";
    }

    @Override
    public void setFieldNames(LogstashFieldNames fieldNames) {
        this.setFieldName(FIELD_USER);
    }

    @Override
    public void writeTo(JsonGenerator generator, ILoggingEvent event) throws IOException {
        JsonWritingUtils.writeStringField(generator, this.getFieldName(), this.getUser(event));
    }
}`

and I have used this class as

`logstashEncoder.getProviders().addProvider(new UserJsonProvider());`

Configuartion will be like this 

`	LogstashTcpSocketAppender logstashAppender = new LogstashTcpSocketAppender();
	logstashAppender.setName(LOGSTASH_APPENDER_NAME);
	logstashAppender.setContext(context);
	LogstashEncoder logstashEncoder = new LogstashEncoder();
	logstashAppender.addDestinations(new InetSocketAddress(jHipsterProperties.getLogging().getLogstash().getHost(), jHipsterProperties.getLogging().getLogstash().getPort()));

	ShortenedThrowableConverter throwableConverter = new ShortenedThrowableConverter();
	throwableConverter.setRootCauseFirst(true);
	logstashEncoder.setThrowableConverter(throwableConverter);
	logstashEncoder.getProviders().addProvider(new UserJsonProvider());
	logstashAppender.setEncoder(logstashEncoder);
	logstashAppender.start();`
but

`Authentication auth = SecurityContextHolder.getContext().getAuthentication();`  always return null.

So How can I get `Authentication` object in `UserJsonProvider`.

I had tried with implementation of 
`public class UserConverter extends ClassicConverter {
    @Override
    public String convert(ILoggingEvent event) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.getName();
        }
        return "NO_USER";
    }
}` 
using "ConsoleAppender"
appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
            <encoder name="enc" class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                <layout class="com.truecom.logging.PatternLayoutWithUserContext">
                    <param name="Pattern" value="%d{HH:mm:ss.SSS} %-5level %logger{10} [%user] - %msg%n" />
                </layout>
            </encoder>
        </appender>

        <root level="${logging.level.root}">
            <appender-ref ref="CONSOLE"/>
        </root>

**Comment by philsttr** [comment]
Hi @nrvmodi ,

The behavior you see is because the TCP appender is asynchronus.  Specifically, log events are serialized to JSON and sent over the TCP connection on a different thread than thread that logged the event.  This is to ensure that slow TCP connections don't slow down your application.

Since the `SecurityContextHolder.getContext()` is backed by a `ThreadLocal`, the context is only available to the thread that logged the event, and is not available to the thread that is serializing the log events.  This is why `SecurityContextHolder.getContext()` returns `null` in your `UserJsonProvider` when using the TCP appender.  i.e. there is no security context for the thread performing the serialization.

The ConsoleAppender, on the other hand, is synchronous.  Therefore serialization happens on the same thread as the thread that logged the event.  And therefore the security context is available.

So, you're not going to be able to reference the `SecurityContextHolder.getContext()` from a `JsonProvider` when using an asynchronous appender, such as the TCP appender.


As an alternative solution, I would recommend placing data that you want included in every log event into the [MDC](http://mcs.une.edu.au/doc/logback/manual/mdc.html) via a filter or something.  The values in the MDC are attached to the log event before it is transferred to the serialization thread, so it is available to the serialization thread.  The MDC provider will add these values to the JSON event, so you don't need to implement your own `JsonProvider`.

As a side note...be mindful that including raw usernames in log events leaks secure information.

**Comment by philsttr** [comment]
You could use a `ServletFilter` _after_ the spring security filter chain (which populates the authentication)...

```java
void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) {
    // Danger: This leaks secure information in log files
    try(MDC.MDCCloseable closeable = MDC.putCloseable("user", getUserName()) {
         chain.doFilter(request, response)
    }
}

String getUserName() {
    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    return auth != null ? auth.getName() : "NO_USER";
}
```
